In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros([3,4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.zeros([3,3,4], dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones([3,4], dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [9]:
3+np.zeros([3,4], dtype=int)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [11]:
np.empty([4,6])  #value of the data is very very less

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 7.56602523e-307, 6.23058028e-307],
       [8.45593934e-307, 7.56593017e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 7.56599128e-307,
        1.42417629e-306, 8.45593934e-307, 6.89805151e-307],
       [1.11260144e-306, 6.89812281e-307, 1.42418172e-306,
        1.37961641e-306, 9.45699679e-308, 2.22522596e-306]])

In [13]:
#create a data inbetween any two numbers 
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [15]:
np.linspace(3,8,100)

array([3.        , 3.05050505, 3.1010101 , 3.15151515, 3.2020202 ,
       3.25252525, 3.3030303 , 3.35353535, 3.4040404 , 3.45454545,
       3.50505051, 3.55555556, 3.60606061, 3.65656566, 3.70707071,
       3.75757576, 3.80808081, 3.85858586, 3.90909091, 3.95959596,
       4.01010101, 4.06060606, 4.11111111, 4.16161616, 4.21212121,
       4.26262626, 4.31313131, 4.36363636, 4.41414141, 4.46464646,
       4.51515152, 4.56565657, 4.61616162, 4.66666667, 4.71717172,
       4.76767677, 4.81818182, 4.86868687, 4.91919192, 4.96969697,
       5.02020202, 5.07070707, 5.12121212, 5.17171717, 5.22222222,
       5.27272727, 5.32323232, 5.37373737, 5.42424242, 5.47474747,
       5.52525253, 5.57575758, 5.62626263, 5.67676768, 5.72727273,
       5.77777778, 5.82828283, 5.87878788, 5.92929293, 5.97979798,
       6.03030303, 6.08080808, 6.13131313, 6.18181818, 6.23232323,
       6.28282828, 6.33333333, 6.38383838, 6.43434343, 6.48484848,
       6.53535354, 6.58585859, 6.63636364, 6.68686869, 6.73737

In [19]:
np.linspace(3,8,10).reshape(2,5)

array([[3.        , 3.55555556, 4.11111111, 4.66666667, 5.22222222],
       [5.77777778, 6.33333333, 6.88888889, 7.44444444, 8.        ]])

In [21]:
np.logspace(3,8,10)

array([1.00000000e+03, 3.59381366e+03, 1.29154967e+04, 4.64158883e+04,
       1.66810054e+05, 5.99484250e+05, 2.15443469e+06, 7.74263683e+06,
       2.78255940e+07, 1.00000000e+08])

In [24]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
a.max()

15

In [27]:
a.max(axis = 0)

array([12, 13, 14, 15])

In [28]:
a.max(axis = 1)

array([ 3,  7, 11, 15])

In [30]:
pow(a,2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [31]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [37]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [38]:
np.log10(a)

C:\Users\Rengarajan\AppData\Local\Temp\ipykernel_24292\547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

# Deep copy and shallow copy

In [39]:
x = np.array([1,2,3,4])

In [41]:
y = x

In [42]:
y

array([1, 2, 3, 4])

In [43]:
z = np.copy(x)

In [44]:
z

array([1, 2, 3, 4])

In [46]:
x[0] = 100

In [49]:
y

array([100,   2,   3,   4])

In [50]:
z

array([1, 2, 3, 4])

# ID

In [51]:
id(x)

2084013846768

In [52]:
id(y)

2084013846768

In [53]:
id(z)

2083999860464

In [54]:
ra = np.array([123,456])

In [55]:
ya = ra

In [56]:
id(ra)

2083999859888

In [57]:
id(ya)

2083999859888

In [59]:
id(ra[0])

2084016384272

In [60]:
id(ya[0])

2084016387792

In [61]:
id(ra[1])

2084016388944

In [62]:
id(ya[1])

2084016384272

In [63]:
id(ya[0]) == id(ra[1])

True