In [1]:
import numpy as np

In [2]:
l = ['raja',1,2,3]
type(l)

list

In [3]:
np.array(l)

array(['raja', '1', '2', '3'], dtype='<U11')

In [4]:
type(np.array(l)) #ndarray - n dimensional array

numpy.ndarray

In [5]:
np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

In [6]:
b = np.array([1,2,3,4.5])
b[1]

2.0

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
a = np.array([[1,2],[3,4]])
a[1][1]

4

In [9]:
c = np.array([1,2,3,4],ndmin=4)
c

array([[[[1, 2, 3, 4]]]])

In [10]:
c[0][0][0][1]

2

In [11]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [12]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [13]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
np.mat([1,2,3,4,5])  #matrix are just 2D elements

matrix([[1, 2, 3, 4, 5]])

In [15]:
np.asanyarray(np.mat([1,2,3,4,5]))

matrix([[1, 2, 3, 4, 5]])

In [16]:
#this fun is for generating array in the required format
np.fromfunction(lambda i,j:i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
np.fromfunction(lambda i,j:i*j ,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [19]:
#numpy always return float, if we want int..
np.fromfunction(lambda i,j:i*j ,(4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [20]:
#numpy always return arrays, if we want into matrix we can change it
np.mat(np.fromfunction(lambda i,j:i*j ,(4,4),dtype=int))

matrix([[0, 0, 0, 0],
        [0, 1, 2, 3],
        [0, 2, 4, 6],
        [0, 3, 6, 9]])

In [22]:
np.fromfunction(lambda i,j,z:i*j*z ,(3,2,2),dtype=int)  #3array in the form of 2*2 array (3 dimensions)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 2]]])

In [23]:
np.fromfunction(lambda i,j,z:i*j*z ,(4,2,2),dtype=int)  #4array in the form of 2*2 array (3 dimension)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 2]],

       [[0, 0],
        [0, 3]]])

In [24]:
np.fromfunction(lambda i,j,z:i*j*z ,(4,2,2))  #4array in the form of 2*2 array (3 dimension)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.]],

       [[0., 0.],
        [0., 2.]],

       [[0., 0.],
        [0., 3.]]])

In [25]:
np.fromfunction(lambda i,j,z,p:i*j*z*p ,(4,3,2,2),dtype=int) #4dimension 3array in the form of 2*2

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [28]:
a = np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2), dtype=int)  #4array in the form of 2*2 array (3 dimension)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [30]:
#to find dimension of the array
a.ndim

3

In [31]:
#size of the array    #we have totally 24 elements
a.size

24

In [32]:
#to find shape of the array
a.shape

(4, 3, 2)

In [33]:
#to find dataype of the array
a.dtype

dtype('int32')

In [34]:
import pandas as pd
a = np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2), dtype=int)  
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [36]:
a = np.fromfunction(lambda i,j:i*j ,(3,3), dtype=int)  
pd.DataFrame(a)              #we can create a table because of 2D

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4

In [38]:
b = np.fromfunction(lambda i,j:i+j ,(100,20), dtype=int)  
pd.DataFrame(b)

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0    0    1    2    3    4    5    6    7    8    9   10   11   12   13   14   
1    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   
2    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   
3    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   
4    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18   
..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
95  95   96   97   98   99  100  101  102  103  104  105  106  107  108  109   
96  96   97   98   99  100  101  102  103  104  105  106  107  108  109  110   
97  97   98   99  100  101  102  103  104  105  106  107  108  109  110  111   
98  98   99  100  101  102  103  104  105  106  107  108  109  110  111  112   
99  99  100  101  102  103  104  105  106  107  108  109  110  111  112  113   

     15   16   17   18   19  
0    15   16   17   18   19  
1    16   17   18   19   20  
2    17   18   19   20   21  
3    18   19   20   21   22  
4    19   20   21   22   23  
..  ...  ...  ...  ...  ...  
95  110  111  112  113  114  
96  111  112  113  114  115  
97  112  113  114  115  116  
98  113  114  115  116  117  
99  114  115  116  117  118  

[100 rows x 20 columns]

In [39]:
#generating random data
np.random.rand(100,4)

array([[1.69842956e-01, 9.64860437e-01, 3.20386286e-01, 4.67767084e-01],
       [8.60382159e-01, 4.77800712e-03, 9.39810118e-01, 6.86263981e-01],
       [9.05138653e-01, 5.45890103e-01, 2.95123064e-01, 1.93398741e-01],
       [2.84920116e-01, 2.37389834e-01, 8.15151130e-01, 7.79865476e-01],
       [7.78980900e-01, 8.66638352e-01, 5.46875160e-01, 2.22305506e-01],
       [4.28853864e-01, 4.50442689e-01, 6.40999886e-01, 5.35840261e-01],
       [7.96897090e-01, 9.34330594e-01, 5.11143792e-01, 6.85001189e-02],
       [6.03325997e-01, 9.46146479e-01, 3.83285705e-01, 5.47216640e-01],
       [5.87395926e-01, 4.69291910e-01, 8.96016288e-01, 9.37830320e-01],
       [6.83285151e-01, 9.17439020e-01, 2.13712742e-01, 6.05016307e-03],
       [6.42114712e-01, 4.12633997e-02, 7.66949552e-01, 3.82940766e-01],
       [4.40345715e-01, 9.52185681e-01, 2.94433823e-01, 9.29862750e-01],
       [5.49976092e-01, 7.24401847e-01, 3.35793326e-01, 6.97699961e-01],
       [3.31199911e-01, 9.36881573e-01, 1.91255457e

In [43]:
np.random.randint(4,50) #this fun generate random int between 4 and 50

11

In [47]:
np.random.randn(4,5) #this fun will generate random numbers which follow normal distribution
                     #by adding all this mean will be zero and SD will be 1

array([[ 1.76188582, -1.17403608,  0.48329741,  1.08524063, -0.48035718],
       [-0.93212409, -1.0009703 , -1.58598211,  0.66279817,  0.8616647 ],
       [ 1.11652646,  1.15243771,  2.32243418, -0.1234997 ,  0.76179244],
       [ 0.35380302, -0.74106382,  2.39483435,  0.2592886 ,  0.87123123]])

In [48]:
#create a dataframe which follows normal distributions
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0 -1.423412 -1.643758  1.640673 -0.728990 -0.541121
1 -0.676371  0.370314 -0.337789  0.605281 -1.359733
2  1.686511 -0.813056 -0.073429  0.357634  0.462792
3  0.536773  1.108667  1.288147 -0.163282 -1.049258

In [57]:
#reshape the dimension of array 
d = np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2), dtype=int) #3D to 2D
d.reshape(8,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [58]:
#reshape the dimension of array
d = np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2), dtype=int) #3D to 4D
d.reshape(2,2,3,2)

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1],
         [0, 2]]],


       [[[0, 0],
         [0, 2],
         [0, 4]],

        [[0, 0],
         [0, 3],
         [0, 6]]]])

In [60]:
#reshape the dimension of array
d = np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2), dtype=int) #3D to 4D
d.reshape(4,-1) #here -1 automaticaly caluclulate the suitable number to get the elemnt(4,6)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [61]:
#reshape the dimension of array
d = np.fromfunction(lambda i,j,z:i*j*z ,(4,3,2), dtype=int) #3D to 4D
d.reshape(4,-134567) #any negative number here automaticaly caluclulate the suitable number to get the elemnt(4,6)notonly-1

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [63]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [64]:
list(range(4,10,0.2)) #range works only int not float

TypeError: 'float' object cannot be interpreted as an integer

In [68]:
#same like range but it works in float also
np.arange(4,10.7,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4,
       10.6])

In [69]:
a = np.arange(4,10.7,0.2)
a[2:10]

array([4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8])

In [71]:
#extract value greater than 0.5
arr = np.random.rand(4,4)
arr

array([[0.39244404, 0.2865547 , 0.48963868, 0.82357841],
       [0.10898029, 0.53065975, 0.85614164, 0.00541956],
       [0.23775303, 0.95787775, 0.25195957, 0.36516494],
       [0.31222206, 0.06362165, 0.27242941, 0.46578101]])

In [74]:
arr[arr<0.5]   #same like pandas we can filter it

array([0.39244404, 0.2865547 , 0.48963868, 0.10898029, 0.00541956,
       0.23775303, 0.25195957, 0.36516494, 0.31222206, 0.06362165,
       0.27242941, 0.46578101])

In [75]:
#filtering specific data
arr

array([[0.39244404, 0.2865547 , 0.48963868, 0.82357841],
       [0.10898029, 0.53065975, 0.85614164, 0.00541956],
       [0.23775303, 0.95787775, 0.25195957, 0.36516494],
       [0.31222206, 0.06362165, 0.27242941, 0.46578101]])

In [76]:
len(arr)

4

In [79]:
arr[[1,2],[2]]    #[1,2] for row, [2]for columns

array([0.85614164, 0.25195957])

In [80]:
arr = np.random.rand(8,4)
arr

array([[0.21028088, 0.57059672, 0.18100268, 0.37838241],
       [0.02459825, 0.30690931, 0.1510157 , 0.32143501],
       [0.82133074, 0.40984543, 0.51476407, 0.58846369],
       [0.44954736, 0.03593264, 0.17022617, 0.37078466],
       [0.11576518, 0.51397483, 0.43586387, 0.24065605],
       [0.0611074 , 0.58712259, 0.08843287, 0.67055864],
       [0.66056423, 0.80624093, 0.42182043, 0.03152249],
       [0.97576126, 0.47843897, 0.15521601, 0.03932978]])

In [83]:
a2 = arr[2:7,0:2]  #row index and column index
a2

array([[0.82133074, 0.40984543],
       [0.44954736, 0.03593264],
       [0.11576518, 0.51397483],
       [0.0611074 , 0.58712259],
       [0.66056423, 0.80624093]])

In [85]:
a2[0][0] = 100  #overriting
a2

array([[1.00000000e+02, 4.09845430e-01],
       [4.49547362e-01, 3.59326356e-02],
       [1.15765177e-01, 5.13974834e-01],
       [6.11074046e-02, 5.87122587e-01],
       [6.60564228e-01, 8.06240935e-01]])

In [89]:
a =np.array([[3,4],[2,3]])
b = np.array([[4,4],[2,3]])

In [90]:
a@b #matrix multiplication

array([[20, 24],
       [14, 17]])

In [91]:
a*b  #elemnent multiplication

array([[12, 16],
       [ 4,  9]])

In [92]:
m = a@b
m/0    #here won't give div by zero error, it gives infinity

C:\Users\Rengarajan\AppData\Local\Temp\ipykernel_6196\3591685889.py:2: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])